services:
  - type: web
    name: wheel-tg-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # Нужно будет установить вручную в панели Render
      - key: WEBAPP_URL
        sync: false  # Будет установлен автоматически после первого деплоя (см. инструкцию)
      - key: PORT
        value: 8000
      - key: DB_PATH
        value: db.sqlite3
      - key: SHOP_ADDRESS
        value: г. Уфа, ул. Трамвайная, д. 13/1
      - key: SHOP_PHONE
        value: +79177364777
    healthCheckPath: /
    autoDeploy: true
